# Site settings
title: Mark Dixon
header-img: img/home-bg.jpg
email: mark@lowla.io
description: "Mark Dixon's Site"
url: "http://www.dixonnet.com"
twitter_username: adnamsale
github_username:  adnamsale

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
